### ISSUE TITLE
Single Key Support

### ISSUE THREAD

**Issue by r888800009** [lydell/LinkHints#15]
### Problem

Hello, I have used Vimium link hints feature, that can use single key shortcut `f` to hint. 
When I configure the `f` key, and this extension seems to require the modifier key.

**Comment by lydell** [comment]
Hi!

Yes, this extension requires modifier keys. I developed another extension similar to Vimium (called VimFx) for many years. I really liked single key shortcuts, but eventually got tired of them not working very well in some situations.

I ended up typing into text fields by mistake. And you can’t just spam <kbd>Escape</kbd> before the shortcut either, because that can accidentally close modals and stuff. And if you press <kbd>Escape</kbd> before the shortcut, it kind isn’t better than a modifier key…

Another thing is that it is really difficult to identify all custom text fields that forums and stuff use. It’s really annoying when you try to type some text but you trigger shortcuts instead.

Single key shortcuts also kind of requires a “prevent autofocus“ feature, which is also really difficult to get right.

So … single key shortcuts is something I feel pretty strongly about. It is complexity I don’t want to add, and something that I don’t want to maintain since I don’t use it (and can’t really recommend it). I wouldn’t want to add a half-good solution either, because people will just be disappointed and open issues that I can’t really help with.

You say you have used Vimium? I’m curious – what made you try out Link Hints? Don’t you miss the rest of Vimium’s features? (You might also be interested in #6, btw.)

**Comment by AtomToast** [comment]
> You say you have used Vimium? I’m curious – what made you try out Link Hints? Don’t you miss the rest of Vimium’s features? (You might also be interested in #6, btw.)

I am somebody else but I just discovered this addon after getting rid of vim-vixen. The main reason is that I had enough from it not working well often enough due to firefoxes limitations and I now use a custom keyboard with custom nav layers etc. So the default firefox shortcuts actually became quite ergonomic. All I was missing was a solid way to get the link hinting, which this seems to provide in a very simple and robust way. Which I highly appreciate. Caret browsing is hardly adequate for this
