### ISSUE TITLE
A toggle to disable Link Hints

### ISSUE THREAD

**Issue by rubaboo** [lydell/LinkHints#19]
Many sites have their own keyboard shortcuts nowadays. It is not always easy to come up with a different non-conflicting shortcut for LinkHints.

It would be handy to have a master switch to toggle LinkHints (I don't mean hints themselves) off and on, as well as a list of sites where LinkHints is off by default but can be enabled with that same master switch.

**Comment by lydell** [comment]
Hi! Can you give a list of sites where you need this, and what shortcuts conflict on each site, please? That would help motivating the feature and understanding the problem better.

**Comment by rubaboo** [comment]
tiddlywiki.com, Alt+J for new journal entry. That's it for now. I thought it would be more, but I checked checkvist.com, dynalist.io and trello.com and they do not conflict. Still, I think it would be useful to at least have a toggle in the toolbar button popup dialog.

**Comment by lydell** [comment]
Thanks! Can you help me learn more about the tiddlywiki use case?

1. Would you like Link Hints to be completely disabled, always, on tiddlywiki.com?
2. If so, wouldn’t you miss being able to use Link Hints for some parts of it?
3. Or would you rather have a button in the toolbar button popup to toggle Link Hints? How would you use that – how do you decide when to enable/disable Link Hints? You can’t just click the toggle before each keyboard shortcut – then you could just as well click the “New journal” button or whatever instead?
4. How often does one make a new journal? Is it seldom enough that you could sacrifice that shortcut, and maybe use Link Hints to click a “New journal” button instead?
5. Have you thought about changing the Link Hints shortcut to something else, that doesn’t conflict with the pages you use? Pros/cons?
6. Would it make sense to have some kind of “let the next shortcut pass through” thing in Link Hints? For example, maybe you could press, say, Ctrl+E followed by Alt+J to let the Alt+J go to the page instead of triggering Link Hints.

Just trying to understand what is the best solution here :) Personally I have had zero keyboard shortcut conflicts so far, so I have no experience myself.

**Comment by rubaboo** [comment]
1. No
2. Yes
3. You got me there.
4. Once a day to a few times a day. Yes.
5. Not really. All cons: it would not be default so I 'd have to remember to set it again when I work in a different Firefox profile; it's hard to find a shortcut that is not used for anything else - I am not able to recall all of them at will, so very likely to pick one that I will later on find conflicting with something else.
6. Not sure. This is basically the same as "master switch" shortcut that I proposed initially, but only effective for one shortcut. Out of the two I would prefer an on/off keyboard shortcut with the toolbar button reflecting the current status. Forget a maintainable list; if you are going to implement the on/off switch, maybe have it remember the sites where it is off.

Overall, you convinced me that it's not a big deal and probably not worth the fuss. Other extensions like Vimium and such have some sort of "ignore" mode, but they make use of a lot more shortcuts, so the chance for a conflict is much higher. I actually got tired of all of them and specifically sought out an extension with minimal functionality - just for clicking links and selecting elements. For everything else there are native Firefox shortcuts that I memorized much better over the years, and more importantly, they are the same across the whole system, like "PgUp" will behave the same in any app, "Ctrl+b" most definitely will not.

I am inclined to have this ticket closed. Thank you for being comprehensive about it. I tried to do the same with my answer.
