### ISSUE TITLE
firefoxPopupBlockerWorkaround should check whether event is from this extension or not

### ISSUE THREAD

**Issue by gdh1995** [lydell/LinkHints#21]
The function is in https://github.com/lydell/LinkHints/blob/efa18fdfbf95016bd706b83a2d51545cb157b440/src/worker/Program.js#L1337-L1631 .

I find it doesn't check `event === the****Event` during handing preventDefault, so if a host page dispatches another "click" event (and even on another element) during this process, then the logic seems problematic.

**Comment by lydell** [comment]
@gdh1995 Hi! Thanks for reporting this, and sorry for taking more than a year to get back to you! In case you still remember what this was all about and are curious: I looked into this today. The code works like this, **synchronously:**

```js
addWorkaround();
dispatchClickEvents();
removeWorkaround();
```

Since all of that runs synchronously (yes, dispatching events and triggering event listeners is actually done synchronously by the browser!), there is no way for other code on the page to trigger events during that time, since JavaScript is single threaded. So I don’t think any more checks are needed!

**Comment by gdh1995** [comment]
> there is no way for other code on the page to trigger events during that time

Um, this line is incorrect. A page may add click listeners, and dispatch another click event during handling the event which would be blocked.

**Comment by lydell** [comment]
Ah, triggering another click _in_ a click listener! Clever! I’ll have to try that out.

**Comment by lydell** [comment]
Thanks for explaining to me how to cause this issue! I have a commit now that fixes it: https://github.com/lydell/LinkHints/commit/f3410bbe8058aae2031598ddabc0cb33f182d6ce
