### ISSUE TITLE
Alt-L opens a new window instead of tab on Vivaldi / Vivaldi support in general

### ISSUE THREAD

**Issue by jzyinq** [lydell/LinkHints#39]
### Steps to reproduce

1. Use Alt-L shortcut in Vivaldi browser
2. Instead opening new tab it will open a new window 

### Description

On Vivaldi browser using a shortcut for opening a new tab actually opens a new window instead.

### Debug info

<details>
<summary>Debug info</summary>

```json
{
  "version": "1.1.1",
  "browser": "chrome",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.126 Safari/537.36",
  "browserInfo": null,
  "platformInfo": {
    "arch": "x86-64",
    "nacl_arch": "x86-64",
    "os": "linux"
  },
  "storage.sync": {},
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US",
  "layout": {}
}
```

</details>

**Comment by lydell** [comment]
Hi! I have never tested Vivaldi, and I don’t really have the bandwidth to do so.

According to the debug info, it seems to behave as Chrome. And for Chrome, I open new tabs like this:

https://github.com/lydell/LinkHints/blob/2a2875ff7d5b08fb9694afa8b74a4563d404db97/src/worker/Program.ts#L408-L424

In other words, by simulating a click on a link with the ctrl and “meta” keys pressed. Not sure if that helps.

**Comment by jzyinq** [comment]
Interesting, using those keys manually indeed opens a new tab as intended. I'll try to figure something out on my own then. Thanks for feedback.

**Comment by jzyinq** [comment]
I found the time to build it locally and it turns out, that indeed Vivaldi has a different set of shortcuts for opening links in background/new tab. 

`shift` + click opens new window in chrome wether in vivaldi it opens link in new tab on foreground.

It's a bit difficult to create a PR for it since browser in both cases is reported as chrome, so I think we can close that issue.

**Comment by jzyinq** [comment]
Ah, and for the record - to launch dev env on vivaldi go with:
```
npm run firefox -- --target chromium --chromium-binary /usr/bin/vivaldi
``` 
Btw kudos for [CONTRIBUTING.md](https://github.com/jzyinq/LinkHints/blob/f8eeb96c99a4a3512e43821bbc90bf516135fd6e/CONTRIBUTING.md) - I'm not even a js dev and I didn't have any issues with assembling this environment.

**Comment by lydell** [comment]
Cool, thanks!

Yes, adding a third browser alternative ("firefox", "chrome", "vivaldi") does sound doable but a lot of work – we’d have to go through all places and decide what to do in the vivaldi case and maybe refactor a bit.

I won’t be doing that myself, but if someone would like to contribute it might be doable with some collaboration.

I think I’m going to keep this issue open until the issue trackers grows out of control, to make it easier for other Vivaldi users to find. Or maybe you are the only Vivaldi users, who knows!

**Comment by sctice** [comment]
I'm running into this problem (holding `alt` while completing a hint opens the link in a new window instead of a new tab in Vivaldi), and I'd really love to come up with a solution. I totally understand not wanting to add first-class support for Vivaldi, but maybe there's a less labor-intensive option? The problem, as I understand it, is just that Vivaldi has made the choice to use shift-click to open a link in a new tab and ctrl-shift-click to open a link in a new window. Because Link Hints uses a simulated mouse click with ctrl+meta+shift to open links in a new tab, in Vivaldi (which is based on Chromium and presumably gets classified as "chrome" in Link Hints) that results in opening the link in a new window.

Perhaps a hidden option along the lines of "prefer windows" to change the simulated mouse click in the "chrome" case? I think that the only behavior change required is to shift-click instead of ctrl-shift-clicking when [handling "OpenNewTab"](https://github.com/lydell/LinkHints/blob/495652ec888fea99526eaf3fd3b679f03819302e/src/worker/Program.ts#L465-L469). I'm imagining a boolean option like "Shift-click opens in new tab".

For what it's worth, I'm a heavy Link Hints user (thank you :heart:), and this is the only issue I've run into trying to use Link Hints in Vivaldi. I don't know that any more extensive effort is required to support Vivaldi perfectly well.

**Comment by lydell** [comment]
> this is the only issue I've run into trying to use Link Hints in Vivaldi

Then that’s probably the only issue. Maybe we can auto-detect Vivaldi just for open-in-new-tab, and not change anything else.

**Comment by lydell** [comment]
If you would like to try that out and make a PR, that would be amazing!
